# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8aeee598ff874453603cbca44b7b42a14b514a99403cef33bd9b4487326aecb7a202eec2f7914ef88818bd1b6dc9fdfb2c6aa9c80ec7bd7cce44da9b0963598f

test:
  secret_key_base: 7459d862f34ae6ef5cc2e45c5f9f6f435a3ef16ca89d213542ec9d9d6304b7d1f6b1e3e5eed22fda6ae4f5dc988daeeddff6ddd0f6385ca693f442b8e98d4e2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
